baseURL = "https://davidhallin.com/"
locale = "en-US"
title = "davidhallin.com"

copyright = "© David Hallin"

[params]
	subtitle = "a blog by david hallin about programming, and learning new things"

	avatar = "/images/dave.png"
	
	featherIconsCDN = true
	favicon = "/favicon.ico"
	mode = "auto" # "dark" or "auto"

[pagination]
  pagerSize = 20
	
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    style = "monokai"

[menu]
    [[menu.main]]
    name = "home"
    url = "/"
    weight = 1

    [[menu.main]]
    name = "readings"
    url = "/tags/readings/"
    weight = 2

    [[menu.main]]
    name = "projects"
    url = "/projects/"
    weight = 3

    [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 4

    [[menu.main]]
    name = "uses"
    url = "/uses/"
    weight = 5

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/hallindavid"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"

[outputs]
home = ["HTML", "RSS", "JSON"]
